//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlApiBindings {

public enum ctl_lace_trigger_flag_t {
  CTL_LACE_TRIGGER_FLAG_AMBIENT_LIGHT = (1 << 0),
  CTL_LACE_TRIGGER_FLAG_FIXED_AGGRESSIVENESS = (1 << 1),
  CTL_LACE_TRIGGER_FLAG_MAX = (1 << 31)
}

}
