//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlApiBindings {

public class ctl_intel_arc_sync_profile_params_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_intel_arc_sync_profile_params_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_intel_arc_sync_profile_params_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_intel_arc_sync_profile_params_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_intel_arc_sync_profile_params_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CtlApiPINVOKE.delete_ctl_intel_arc_sync_profile_params_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_intel_arc_sync_profile_t IntelArcSyncProfile {
    set {
      CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_IntelArcSyncProfile_set(swigCPtr, (int)value);
    } 
    get {
      ctl_intel_arc_sync_profile_t ret = (ctl_intel_arc_sync_profile_t)CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_IntelArcSyncProfile_get(swigCPtr);
      return ret;
    } 
  }

  public float MaxRefreshRateInHz {
    set {
      CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_MaxRefreshRateInHz_set(swigCPtr, value);
    } 
    get {
      float ret = CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_MaxRefreshRateInHz_get(swigCPtr);
      return ret;
    } 
  }

  public float MinRefreshRateInHz {
    set {
      CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_MinRefreshRateInHz_set(swigCPtr, value);
    } 
    get {
      float ret = CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_MinRefreshRateInHz_get(swigCPtr);
      return ret;
    } 
  }

  public uint MaxFrameTimeIncreaseInUs {
    set {
      CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_MaxFrameTimeIncreaseInUs_set(swigCPtr, value);
    } 
    get {
      uint ret = CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_MaxFrameTimeIncreaseInUs_get(swigCPtr);
      return ret;
    } 
  }

  public uint MaxFrameTimeDecreaseInUs {
    set {
      CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_MaxFrameTimeDecreaseInUs_set(swigCPtr, value);
    } 
    get {
      uint ret = CtlApiPINVOKE.ctl_intel_arc_sync_profile_params_t_MaxFrameTimeDecreaseInUs_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_intel_arc_sync_profile_params_t() : this(CtlApiPINVOKE.new_ctl_intel_arc_sync_profile_params_t(), true) {
  }

}

}
