//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlApiBindings {

public enum ctl_3d_feature_misc_flag_t {
  CTL_3D_FEATURE_MISC_FLAG_DX11 = (1 << 0),
  CTL_3D_FEATURE_MISC_FLAG_DX12 = (1 << 1),
  CTL_3D_FEATURE_MISC_FLAG_VULKAN = (1 << 2),
  CTL_3D_FEATURE_MISC_FLAG_LIVE_CHANGE = (1 << 3),
  CTL_3D_FEATURE_MISC_FLAG_MAX = (1 << 31)
}

}
