//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlApiBindings {

public enum ctl_operation_type_t {
  CTL_OPERATION_TYPE_READ = 1,
  CTL_OPERATION_TYPE_WRITE = 2,
  CTL_OPERATION_TYPE_MAX
}

}
