//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlApiBindings {

public class ctl_oc_properties_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_oc_properties_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_oc_properties_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_oc_properties_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_oc_properties_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CtlApiPINVOKE.delete_ctl_oc_properties_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      CtlApiPINVOKE.ctl_oc_properties_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = CtlApiPINVOKE.ctl_oc_properties_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      CtlApiPINVOKE.ctl_oc_properties_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = CtlApiPINVOKE.ctl_oc_properties_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public bool bSupported {
    set {
      CtlApiPINVOKE.ctl_oc_properties_t_bSupported_set(swigCPtr, value);
    } 
    get {
      bool ret = CtlApiPINVOKE.ctl_oc_properties_t_bSupported_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_oc_control_info_t gpuFrequencyOffset {
    set {
      CtlApiPINVOKE.ctl_oc_properties_t_gpuFrequencyOffset_set(swigCPtr, ctl_oc_control_info_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlApiPINVOKE.ctl_oc_properties_t_gpuFrequencyOffset_get(swigCPtr);
      ctl_oc_control_info_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_oc_control_info_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_oc_control_info_t gpuVoltageOffset {
    set {
      CtlApiPINVOKE.ctl_oc_properties_t_gpuVoltageOffset_set(swigCPtr, ctl_oc_control_info_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlApiPINVOKE.ctl_oc_properties_t_gpuVoltageOffset_get(swigCPtr);
      ctl_oc_control_info_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_oc_control_info_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_oc_control_info_t vramFrequencyOffset {
    set {
      CtlApiPINVOKE.ctl_oc_properties_t_vramFrequencyOffset_set(swigCPtr, ctl_oc_control_info_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlApiPINVOKE.ctl_oc_properties_t_vramFrequencyOffset_get(swigCPtr);
      ctl_oc_control_info_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_oc_control_info_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_oc_control_info_t vramVoltageOffset {
    set {
      CtlApiPINVOKE.ctl_oc_properties_t_vramVoltageOffset_set(swigCPtr, ctl_oc_control_info_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlApiPINVOKE.ctl_oc_properties_t_vramVoltageOffset_get(swigCPtr);
      ctl_oc_control_info_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_oc_control_info_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_oc_control_info_t powerLimit {
    set {
      CtlApiPINVOKE.ctl_oc_properties_t_powerLimit_set(swigCPtr, ctl_oc_control_info_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlApiPINVOKE.ctl_oc_properties_t_powerLimit_get(swigCPtr);
      ctl_oc_control_info_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_oc_control_info_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_oc_control_info_t temperatureLimit {
    set {
      CtlApiPINVOKE.ctl_oc_properties_t_temperatureLimit_set(swigCPtr, ctl_oc_control_info_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlApiPINVOKE.ctl_oc_properties_t_temperatureLimit_get(swigCPtr);
      ctl_oc_control_info_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_oc_control_info_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_oc_properties_t() : this(CtlApiPINVOKE.new_ctl_oc_properties_t(), true) {
  }

}

}
