//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlApiBindings {

public enum ctl_init_flag_t {
  CTL_INIT_FLAG_USE_LEVEL_ZERO = (1 << 0),
  CTL_INIT_FLAG_MAX = (1 << 31)
}

}
