//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlApiBindings {

public class ctl_oc_control_info_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_oc_control_info_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_oc_control_info_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_oc_control_info_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_oc_control_info_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CtlApiPINVOKE.delete_ctl_oc_control_info_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool bSupported {
    set {
      CtlApiPINVOKE.ctl_oc_control_info_t_bSupported_set(swigCPtr, value);
    } 
    get {
      bool ret = CtlApiPINVOKE.ctl_oc_control_info_t_bSupported_get(swigCPtr);
      return ret;
    } 
  }

  public bool bRelative {
    set {
      CtlApiPINVOKE.ctl_oc_control_info_t_bRelative_set(swigCPtr, value);
    } 
    get {
      bool ret = CtlApiPINVOKE.ctl_oc_control_info_t_bRelative_get(swigCPtr);
      return ret;
    } 
  }

  public bool bReference {
    set {
      CtlApiPINVOKE.ctl_oc_control_info_t_bReference_set(swigCPtr, value);
    } 
    get {
      bool ret = CtlApiPINVOKE.ctl_oc_control_info_t_bReference_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_units_t units {
    set {
      CtlApiPINVOKE.ctl_oc_control_info_t_units_set(swigCPtr, (int)value);
    } 
    get {
      ctl_units_t ret = (ctl_units_t)CtlApiPINVOKE.ctl_oc_control_info_t_units_get(swigCPtr);
      return ret;
    } 
  }

  public double min {
    set {
      CtlApiPINVOKE.ctl_oc_control_info_t_min_set(swigCPtr, value);
    } 
    get {
      double ret = CtlApiPINVOKE.ctl_oc_control_info_t_min_get(swigCPtr);
      return ret;
    } 
  }

  public double max {
    set {
      CtlApiPINVOKE.ctl_oc_control_info_t_max_set(swigCPtr, value);
    } 
    get {
      double ret = CtlApiPINVOKE.ctl_oc_control_info_t_max_get(swigCPtr);
      return ret;
    } 
  }

  public double step {
    set {
      CtlApiPINVOKE.ctl_oc_control_info_t_step_set(swigCPtr, value);
    } 
    get {
      double ret = CtlApiPINVOKE.ctl_oc_control_info_t_step_get(swigCPtr);
      return ret;
    } 
  }

  public double Default {
    set {
      CtlApiPINVOKE.ctl_oc_control_info_t_Default_set(swigCPtr, value);
    } 
    get {
      double ret = CtlApiPINVOKE.ctl_oc_control_info_t_Default_get(swigCPtr);
      return ret;
    } 
  }

  public double reference {
    set {
      CtlApiPINVOKE.ctl_oc_control_info_t_reference_set(swigCPtr, value);
    } 
    get {
      double ret = CtlApiPINVOKE.ctl_oc_control_info_t_reference_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_oc_control_info_t() : this(CtlApiPINVOKE.new_ctl_oc_control_info_t(), true) {
  }

}

}
