//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlApiBindings {

public enum ctl_engine_group_t {
  CTL_ENGINE_GROUP_GT = 0,
  CTL_ENGINE_GROUP_RENDER = 1,
  CTL_ENGINE_GROUP_MEDIA = 2,
  CTL_ENGINE_GROUP_MAX
}

}
